//
// AUTOMATICALLY GENERATED: DO NOT EDIT
// @generated by gen-class-map.cpp
// ../tools/bootstrap/gen-class-map
//   --system
//   /tmp/hhvm-3.11.1/hphp/system/class_map.cpp
//   /tmp/hhvm-3.11.1/hphp/system/constants.h
//   /tmp/hhvm-3.11.1/hphp/system/idl/constants.idl.json
//   /tmp/hhvm-3.11.1/hphp/runtime/ext/collections/../../../system/idl/collections.idl.json
//   /tmp/hhvm-3.11.1/hphp/runtime/ext/std/../../../system/idl/closure.idl.json
//
#ifndef _H_SYSTEM_CONSTANTS
#define _H_SYSTEM_CONSTANTS
namespace HPHP {
struct StaticString;
struct Variant;
extern const int64_t k_MCC_ACCESSPOINT_DOWN;
extern const int64_t k_MCC_ACCESSPOINT_UP;
} // namespace HPHP
#endif // _H_SYSTEM_CONSTANTS
