# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/hhvm-3.12.1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/hhvm-3.12.1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/hhvm-3.12.1/CMakeFiles /tmp/hhvm-3.12.1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/hhvm-3.12.1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named timelib

# Build rule for target.
timelib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timelib
.PHONY : timelib

# fast build rule for target.
timelib/fast:
	$(MAKE) -f third-party/timelib/CMakeFiles/timelib.dir/build.make third-party/timelib/CMakeFiles/timelib.dir/build
.PHONY : timelib/fast

#=============================================================================
# Target rules for targets named folly

# Build rule for target.
folly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 folly
.PHONY : folly

# fast build rule for target.
folly/fast:
	$(MAKE) -f third-party/folly/CMakeFiles/folly.dir/build.make third-party/folly/CMakeFiles/folly.dir/build
.PHONY : folly/fast

#=============================================================================
# Target rules for targets named wangle

# Build rule for target.
wangle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wangle
.PHONY : wangle

# fast build rule for target.
wangle/fast:
	$(MAKE) -f third-party/wangle/CMakeFiles/wangle.dir/build.make third-party/wangle/CMakeFiles/wangle.dir/build
.PHONY : wangle/fast

#=============================================================================
# Target rules for targets named hphp_proxygen

# Build rule for target.
hphp_proxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hphp_proxygen
.PHONY : hphp_proxygen

# fast build rule for target.
hphp_proxygen/fast:
	$(MAKE) -f third-party/proxygen/CMakeFiles/hphp_proxygen.dir/build.make third-party/proxygen/CMakeFiles/hphp_proxygen.dir/build
.PHONY : hphp_proxygen/fast

#=============================================================================
# Target rules for targets named hphp_thrift

# Build rule for target.
hphp_thrift: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hphp_thrift
.PHONY : hphp_thrift

# fast build rule for target.
hphp_thrift/fast:
	$(MAKE) -f third-party/thrift/CMakeFiles/hphp_thrift.dir/build.make third-party/thrift/CMakeFiles/hphp_thrift.dir/build
.PHONY : hphp_thrift/fast

#=============================================================================
# Target rules for targets named afdt

# Build rule for target.
afdt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 afdt
.PHONY : afdt

# fast build rule for target.
afdt/fast:
	$(MAKE) -f third-party/libafdt/CMakeFiles/afdt.dir/build.make third-party/libafdt/CMakeFiles/afdt.dir/build
.PHONY : afdt/fast

#=============================================================================
# Target rules for targets named eaw_table

# Build rule for target.
eaw_table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eaw_table
.PHONY : eaw_table

# fast build rule for target.
eaw_table/fast:
	$(MAKE) -f third-party/libmbfl/mbfl/CMakeFiles/eaw_table.dir/build.make third-party/libmbfl/mbfl/CMakeFiles/eaw_table.dir/build
.PHONY : eaw_table/fast

#=============================================================================
# Target rules for targets named mbfl

# Build rule for target.
mbfl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mbfl
.PHONY : mbfl

# fast build rule for target.
mbfl/fast:
	$(MAKE) -f third-party/libmbfl/mbfl/CMakeFiles/mbfl.dir/build.make third-party/libmbfl/mbfl/CMakeFiles/mbfl.dir/build
.PHONY : mbfl/fast

#=============================================================================
# Target rules for targets named re2

# Build rule for target.
re2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 re2
.PHONY : re2

# fast build rule for target.
re2/fast:
	$(MAKE) -f third-party/re2/CMakeFiles/re2.dir/build.make third-party/re2/CMakeFiles/re2.dir/build
.PHONY : re2/fast

#=============================================================================
# Target rules for targets named squangle

# Build rule for target.
squangle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 squangle
.PHONY : squangle

# fast build rule for target.
squangle/fast:
	$(MAKE) -f third-party/squangle/CMakeFiles/squangle.dir/build.make third-party/squangle/CMakeFiles/squangle.dir/build
.PHONY : squangle/fast

#=============================================================================
# Target rules for targets named webscalesqlclient

# Build rule for target.
webscalesqlclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 webscalesqlclient
.PHONY : webscalesqlclient

# fast build rule for target.
webscalesqlclient/fast:
	$(MAKE) -f third-party/webscalesqlclient/CMakeFiles/webscalesqlclient.dir/build.make third-party/webscalesqlclient/CMakeFiles/webscalesqlclient.dir/build
.PHONY : webscalesqlclient/fast

#=============================================================================
# Target rules for targets named mcrouter

# Build rule for target.
mcrouter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcrouter
.PHONY : mcrouter

# fast build rule for target.
mcrouter/fast:
	$(MAKE) -f third-party/mcrouter/CMakeFiles/mcrouter.dir/build.make third-party/mcrouter/CMakeFiles/mcrouter.dir/build
.PHONY : mcrouter/fast

#=============================================================================
# Target rules for targets named fastlz

# Build rule for target.
fastlz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fastlz
.PHONY : fastlz

# fast build rule for target.
fastlz/fast:
	$(MAKE) -f third-party/fastlz/CMakeFiles/fastlz.dir/build.make third-party/fastlz/CMakeFiles/fastlz.dir/build
.PHONY : fastlz/fast

#=============================================================================
# Target rules for targets named double-conversion

# Build rule for target.
double-conversion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 double-conversion
.PHONY : double-conversion

# fast build rule for target.
double-conversion/fast:
	$(MAKE) -f third-party/double-conversion/CMakeFiles/double-conversion.dir/build.make third-party/double-conversion/CMakeFiles/double-conversion.dir/build
.PHONY : double-conversion/fast

#=============================================================================
# Target rules for targets named zip_static

# Build rule for target.
zip_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zip_static
.PHONY : zip_static

# fast build rule for target.
zip_static/fast:
	$(MAKE) -f third-party/libzip/CMakeFiles/zip_static.dir/build.make third-party/libzip/CMakeFiles/zip_static.dir/build
.PHONY : zip_static/fast

#=============================================================================
# Target rules for targets named gen-class-map

# Build rule for target.
gen-class-map: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen-class-map
.PHONY : gen-class-map

# fast build rule for target.
gen-class-map/fast:
	$(MAKE) -f hphp/tools/bootstrap/CMakeFiles/gen-class-map.dir/build.make hphp/tools/bootstrap/CMakeFiles/gen-class-map.dir/build
.PHONY : gen-class-map/fast

#=============================================================================
# Target rules for targets named gen-ext-hhvm

# Build rule for target.
gen-ext-hhvm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen-ext-hhvm
.PHONY : gen-ext-hhvm

# fast build rule for target.
gen-ext-hhvm/fast:
	$(MAKE) -f hphp/tools/bootstrap/CMakeFiles/gen-ext-hhvm.dir/build.make hphp/tools/bootstrap/CMakeFiles/gen-ext-hhvm.dir/build
.PHONY : gen-ext-hhvm/fast

#=============================================================================
# Target rules for targets named gen-infotabs

# Build rule for target.
gen-infotabs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen-infotabs
.PHONY : gen-infotabs

# fast build rule for target.
gen-infotabs/fast:
	$(MAKE) -f hphp/tools/bootstrap/CMakeFiles/gen-infotabs.dir/build.make hphp/tools/bootstrap/CMakeFiles/gen-infotabs.dir/build
.PHONY : gen-infotabs/fast

#=============================================================================
# Target rules for targets named hfsort

# Build rule for target.
hfsort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hfsort
.PHONY : hfsort

# fast build rule for target.
hfsort/fast:
	$(MAKE) -f hphp/tools/hfsort/CMakeFiles/hfsort.dir/build.make hphp/tools/hfsort/CMakeFiles/hfsort.dir/build
.PHONY : hfsort/fast

#=============================================================================
# Target rules for targets named jit_sort

# Build rule for target.
jit_sort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jit_sort
.PHONY : jit_sort

# fast build rule for target.
jit_sort/fast:
	$(MAKE) -f hphp/tools/hfsort/CMakeFiles/jit_sort.dir/build.make hphp/tools/hfsort/CMakeFiles/jit_sort.dir/build
.PHONY : jit_sort/fast

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) -f hphp/tools/version/CMakeFiles/version.dir/build.make hphp/tools/version/CMakeFiles/version.dir/build
.PHONY : version/fast

#=============================================================================
# Target rules for targets named hphp_analysis

# Build rule for target.
hphp_analysis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hphp_analysis
.PHONY : hphp_analysis

# fast build rule for target.
hphp_analysis/fast:
	$(MAKE) -f hphp/compiler/CMakeFiles/hphp_analysis.dir/build.make hphp/compiler/CMakeFiles/hphp_analysis.dir/build
.PHONY : hphp_analysis/fast

#=============================================================================
# Target rules for targets named hack

# Build rule for target.
hack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hack
.PHONY : hack

# fast build rule for target.
hack/fast:
	$(MAKE) -f hphp/hack/CMakeFiles/hack.dir/build.make hphp/hack/CMakeFiles/hack.dir/build
.PHONY : hack/fast

#=============================================================================
# Target rules for targets named hack_test

# Build rule for target.
hack_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hack_test
.PHONY : hack_test

# fast build rule for target.
hack_test/fast:
	$(MAKE) -f hphp/hack/CMakeFiles/hack_test.dir/build.make hphp/hack/CMakeFiles/hack_test.dir/build
.PHONY : hack_test/fast

#=============================================================================
# Target rules for targets named hphp_hhbbc

# Build rule for target.
hphp_hhbbc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hphp_hhbbc
.PHONY : hphp_hhbbc

# fast build rule for target.
hphp_hhbbc/fast:
	$(MAKE) -f hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/build.make hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/build
.PHONY : hphp_hhbbc/fast

#=============================================================================
# Target rules for targets named neo

# Build rule for target.
neo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 neo
.PHONY : neo

# fast build rule for target.
neo/fast:
	$(MAKE) -f hphp/neo/CMakeFiles/neo.dir/build.make hphp/neo/CMakeFiles/neo.dir/build
.PHONY : neo/fast

#=============================================================================
# Target rules for targets named hphp_parser

# Build rule for target.
hphp_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hphp_parser
.PHONY : hphp_parser

# fast build rule for target.
hphp_parser/fast:
	$(MAKE) -f hphp/parser/CMakeFiles/hphp_parser.dir/build.make hphp/parser/CMakeFiles/hphp_parser.dir/build
.PHONY : hphp_parser/fast

#=============================================================================
# Target rules for targets named hphp_runtime_static

# Build rule for target.
hphp_runtime_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hphp_runtime_static
.PHONY : hphp_runtime_static

# fast build rule for target.
hphp_runtime_static/fast:
	$(MAKE) -f hphp/runtime/CMakeFiles/hphp_runtime_static.dir/build.make hphp/runtime/CMakeFiles/hphp_runtime_static.dir/build
.PHONY : hphp_runtime_static/fast

#=============================================================================
# Target rules for targets named hphp_runtime_ext

# Build rule for target.
hphp_runtime_ext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hphp_runtime_ext
.PHONY : hphp_runtime_ext

# fast build rule for target.
hphp_runtime_ext/fast:
	$(MAKE) -f hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/build.make hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/build
.PHONY : hphp_runtime_ext/fast

#=============================================================================
# Target rules for targets named ext_hhvm_static

# Build rule for target.
ext_hhvm_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ext_hhvm_static
.PHONY : ext_hhvm_static

# fast build rule for target.
ext_hhvm_static/fast:
	$(MAKE) -f hphp/runtime/ext_hhvm/CMakeFiles/ext_hhvm_static.dir/build.make hphp/runtime/ext_hhvm/CMakeFiles/ext_hhvm_static.dir/build
.PHONY : ext_hhvm_static/fast

#=============================================================================
# Target rules for targets named dso_test

# Build rule for target.
dso_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dso_test
.PHONY : dso_test

# fast build rule for target.
dso_test/fast:
	$(MAKE) -f hphp/runtime/ext_zend_compat/CMakeFiles/dso_test.dir/build.make hphp/runtime/ext_zend_compat/CMakeFiles/dso_test.dir/build
.PHONY : dso_test/fast

#=============================================================================
# Target rules for targets named hphp_ext_zend_compat

# Build rule for target.
hphp_ext_zend_compat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hphp_ext_zend_compat
.PHONY : hphp_ext_zend_compat

# fast build rule for target.
hphp_ext_zend_compat/fast:
	$(MAKE) -f hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/build.make hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/build
.PHONY : hphp_ext_zend_compat/fast

#=============================================================================
# Target rules for targets named hphp_system

# Build rule for target.
hphp_system: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hphp_system
.PHONY : hphp_system

# fast build rule for target.
hphp_system/fast:
	$(MAKE) -f hphp/system/CMakeFiles/hphp_system.dir/build.make hphp/system/CMakeFiles/hphp_system.dir/build
.PHONY : hphp_system/fast

#=============================================================================
# Target rules for targets named systemlib

# Build rule for target.
systemlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemlib
.PHONY : systemlib

# fast build rule for target.
systemlib/fast:
	$(MAKE) -f hphp/system/CMakeFiles/systemlib.dir/build.make hphp/system/CMakeFiles/systemlib.dir/build
.PHONY : systemlib/fast

#=============================================================================
# Target rules for targets named hphp_util

# Build rule for target.
hphp_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hphp_util
.PHONY : hphp_util

# fast build rule for target.
hphp_util/fast:
	$(MAKE) -f hphp/util/CMakeFiles/hphp_util.dir/build.make hphp/util/CMakeFiles/hphp_util.dir/build
.PHONY : hphp_util/fast

#=============================================================================
# Target rules for targets named ppc64-asm

# Build rule for target.
ppc64-asm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppc64-asm
.PHONY : ppc64-asm

# fast build rule for target.
ppc64-asm/fast:
	$(MAKE) -f hphp/ppc64-asm/CMakeFiles/ppc64-asm.dir/build.make hphp/ppc64-asm/CMakeFiles/ppc64-asm.dir/build
.PHONY : ppc64-asm/fast

#=============================================================================
# Target rules for targets named vixl

# Build rule for target.
vixl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vixl
.PHONY : vixl

# fast build rule for target.
vixl/fast:
	$(MAKE) -f hphp/vixl/CMakeFiles/vixl.dir/build.make hphp/vixl/CMakeFiles/vixl.dir/build
.PHONY : vixl/fast

#=============================================================================
# Target rules for targets named hphp_zend

# Build rule for target.
hphp_zend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hphp_zend
.PHONY : hphp_zend

# fast build rule for target.
hphp_zend/fast:
	$(MAKE) -f hphp/zend/CMakeFiles/hphp_zend.dir/build.make hphp/zend/CMakeFiles/hphp_zend.dir/build
.PHONY : hphp_zend/fast

#=============================================================================
# Target rules for targets named hhvm

# Build rule for target.
hhvm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hhvm
.PHONY : hhvm

# fast build rule for target.
hhvm/fast:
	$(MAKE) -f hphp/hhvm/CMakeFiles/hhvm.dir/build.make hphp/hhvm/CMakeFiles/hhvm.dir/build
.PHONY : hhvm/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... timelib"
	@echo "... folly"
	@echo "... wangle"
	@echo "... hphp_proxygen"
	@echo "... hphp_thrift"
	@echo "... afdt"
	@echo "... eaw_table"
	@echo "... mbfl"
	@echo "... re2"
	@echo "... squangle"
	@echo "... webscalesqlclient"
	@echo "... mcrouter"
	@echo "... fastlz"
	@echo "... double-conversion"
	@echo "... zip_static"
	@echo "... gen-class-map"
	@echo "... gen-ext-hhvm"
	@echo "... gen-infotabs"
	@echo "... hfsort"
	@echo "... jit_sort"
	@echo "... version"
	@echo "... hphp_analysis"
	@echo "... hack"
	@echo "... hack_test"
	@echo "... hphp_hhbbc"
	@echo "... neo"
	@echo "... hphp_parser"
	@echo "... hphp_runtime_static"
	@echo "... hphp_runtime_ext"
	@echo "... ext_hhvm_static"
	@echo "... dso_test"
	@echo "... hphp_ext_zend_compat"
	@echo "... hphp_system"
	@echo "... systemlib"
	@echo "... hphp_util"
	@echo "... ppc64-asm"
	@echo "... vixl"
	@echo "... hphp_zend"
	@echo "... hhvm"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

